Instance: plandefinition-drug-pq-ex1-validation-protocol
InstanceOf: PlanDefinition
Usage: #example
* meta.profile = "http://hl7.org/fhir/uv/pharm-quality/StructureDefinition/PlanDefinition-drug-pq"
* url = "http://example-server.com/fhir/PlanDefinition/plandefinition-drug-pq-ex1-validation-protocol"
* title = "DP PROCESS VALIDATION"
* type.coding[0] = $plan-definition-type#workflow-definition "Workflow Definition"
* type.coding[+] = $pharmaceutical-plan-type#process-validation "Process Validation"
* status = #active
* subjectReference = Reference(MedicinalProductDefinition/medicinalproductdefinition-drug-product-pq-ex1)
* description = "Pre-defined validation acceptance criteria were established based on manufacturing development data derived from process characterization studies..."
* action[0].title = "Formulation Buffer Preparation Process Parameter Step"
* action[=].code.coding = $manufacturing-step#FormulationBufferPreparationProcessParameterStep "Formulation Buffer Preparation Process Parameter Step"
* action[=].code.text = "Formulation Buffer Preparation Process Parameter Step"
* action[=].action.title = "Formulation Buffer Preparation Process Parameter Step"
* action[=].action.code.text = "FormulationBufferPreparationProcessParameterStep"
* action[=].action.action[0].code.text = "Conclusion"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/22515a3c-5034-448a-9c19-938ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fd17b5d6-9fe1-91c2-2d06-47cb5b295e72"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fc17b5d5-9fe1-91c2-2d06-47cb5b295e73"
* action[+].title = "Formulation Buffer Preparation Performance Indicator Results"
* action[=].code.coding = $manufacturing-step#FormulationBufferPreparationPerformanceIndicatorStep "Formulation Buffer Preparation Performance Indicator Results"
* action[=].action.title = "???"
* action[=].action.code.text = "???"
* action[=].action.action[0].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fc17b5d6-9fe1-91c2-2d16-47cb5b295e72"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64525a3c-5034-448a-9c19-938ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515a3c-5134-448a-9c19-939ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b3c-5134-448a-9c19-939ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b3c-5134-448a-9c19-949ce1958424"
* action[+].title = "Thawing and Formulation Process Parameter Results"
* action[=].code.coding = $manufacturing-step#ThawingandFormulationProcessParameterResultsStep "Thawing and Formulation Process Parameter Resultss"
* action[=].action.title = "???"
* action[=].action.code.text = "???"
* action[=].action.action[0].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/74515a3c-5034-448a-9c19-938ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fc27b5d6-9fe2-91c2-2d16-47cb5b295e72"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fc17b5d5-9fe1-91c2-2d06-47cb5b295e72"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fc27b5d5-9fe1-92c2-2d06-47cb5b295e73"
* action[+].title = "Thawing and Formulation Performance Indicator Results"
* action[=].code.coding = $manufacturing-step#ThawingandFormulationPerformanceIndicatorResultsStep "Thawing and Formulation Performance Indicator Results"
* action[=].action.title = "???"
* action[=].action.code.text = "???"
* action[=].action.action[0].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fc27b5d6-9fe1-91c2-2d16-47cb5b295e72"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515a3c-5034-448a-9c19-938ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/74515a3c-5134-448a-9c19-939ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b4c-5134-448a-9c19-949ce1958424"
* action[=].action.action[+].code.text = "Test"
* action[=].action.action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b3c-5134-448a-9c19-949ce1958434"
* action[+].title = "Bioburden Reduction Filtration Process Parameter Results"
* action[=].code.coding = $manufacturing-step#BioburdenReductionFiltrationProcessParameterResultsStep "Bioburden Reduction Filtration Process Parameter Results"
* action[=].action.code.text = "Test"
* action[=].action.definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/74515b3c-5134-448a-9c19-949ce1958434"
* action[+].title = "Bioburden Reduction Filtration Performance Indicator Results"
* action[=].code.coding = $manufacturing-step#BioburdenReductionFiltrationPerformanceIndicatorResultsStep "Bioburden Reduction Filtration Performance Indicator Results"
* action[=].action[0].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b3c-5134-448a-9c19-939ce1958434"
* action[=].action[+].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/75515b3c-5134-448a-9c19-949ce1958434"
* action[+].title = "Media Challenge Hold Times"
* action[=].code.coding = $manufacturing-step#MediaChallengeHoldTimesStep "Media Challenge Hold Times"
* action[=].action.code.text = "Test"
* action[=].action.definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/75515c3c-5134-448a-9c19-949ce1958434"
* action[+].title = "Media Challenge Results"
* action[=].code.coding = $manufacturing-step#MediaChallengeResultsStep "Media Challenge Results"
* action[=].action[0].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b3c-5134-448a-9c19-939ce1958524"
* action[=].action[+].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b3c-5134-448a-9d19-939ce1958524"
* action[+].title = "Filtered Formulated Drug Product Performance Indicator Results"
* action[=].code.coding = $manufacturing-step#FilteredFormulatedDrugProductPerformanceIndicatorResultsStep "Filtered Formulated Drug Product Performance Indicator Results"
* action[=].action[0].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64525a3d-5034-448a-9c19-938ce1958424"
* action[=].action[+].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64525a4d-5034-448a-9c19-938ce1958424"
* action[=].action[+].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64525a33-5034-448a-9c19-938ce1958424"
* action[+].title = "Fill Weight Summary"
* action[=].code.coding = $manufacturing-step#FillWeightSummaryStep "Fill Weight Summary"
* action[=].action.code.text = "Test"
* action[=].action.definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64515b3c-5134-448a-9c19-939ce2958524"
* action[+].title = "Filling Homogeneity Quality Attributes"
* action[=].code.coding = $manufacturing-step#FillingHomogeneityQualityAttributesStep "Filling Homogeneity Quality Attributes"
* action[=].code.text = "Filling Homogeneity Quality Attributes"
* action[=].action.code.text = "Conclusion"
* action[=].action.definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/22525a3c-5035-448a-9c19-938ce1958424"
* action[+].title = "Filling Results Summary"
* action[=].code.coding = $manufacturing-step#FillingResultsSummaryStep "Filling Results Summary"
* action[=].action[0].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/74515b3c-5134-448a-9c19-939ce1958524"
* action[=].action[+].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/74515b3c-5234-448a-9c19-939ce1958524"
* action[+].title = "Statistical Evaluation of Homogeneity Data"
* action[=].code.coding = $manufacturing-step#StatisticalEvaluationOfHomogeneityDataStep "Statistical Evaluation of Homogeneity Data"
* action[=].action[0].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/74515b3c-5134-448a-9c19-939ce1958534"
* action[=].action[+].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/74515b3c-5234-448a-9c19-939ce1958524"
* action[+].title = "Consistency of the Lyophilization Process"
* action[=].code.coding = $manufacturing-step#ConsistencyoftheLyophilizationProcessStep "Consistency of the Lyophilization Process"
* action[=].action[0].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/fc27b6d6-9fe2-91c2-2d16-47cb5b295e72"
* action[=].action[+].code.text = "Definition"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ActivityDefinition/b664977d-799d-a1ce-928a-6def2a9955bd"
* action[+].title = "Lyophilization Homogeneity"
* action[=].code.coding = $manufacturing-step#LyophilizationHomogeneityStep "Lyophilization Homogeneity Results"
* action[=].action[0].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64525a3d-5134-448a-9c19-938ce1958424"
* action[=].action[+].code.text = "Test"
* action[=].action[=].definitionCanonical = "http://example-server.com/fhir/ObservationDefinition/64525a3d-5144-448a-9c19-938ce1958424"
